### ISSUE TITLE
Man pages + installation path + update flag

### ISSUE THREAD

**Issue by YannMagnin** [GreenDjango/blih_cli#1]
Short issue to know if you will add man pages and if, during the installation step, you can install `blih_cli` in the `/usr/local/bin/` ?

If you can do that, what about a possible `update` flag ? And can you allow me to push a `blih_cli` packet on the `Arch User Repository` (AUR) ?

**Comment by GreenDjango** [comment]
Future features : 
- add `sudo sh install.sh`, who compile and add `blih_cli` to `/user/bin/local`
- add `-U` flag for check update

For AUR it's okay, the project has MIT License
