### ISSUE TITLE
man page missing + uninstall flags

### ISSUE THREAD

**Issue by YannMagnin** [GreenDjango/blih_cli#2]
The copy of `manpage.1.gz` (man pages) seems to fail during the copies. As I can see, you try to move it into `/usr/local/share/man/man1` but you do not check if the folder exist.

Can you also add the `--uninstall` flags ?

**Comment by GreenDjango** [comment]
yes, Paquity.

**Comment by K-daudau** [comment]
bad projet

**Comment by K-daudau** [comment]
Souleve ur mother
